#!/usr/bin/env python3
r"""
Build a Word-submission package from a LaTeX manuscript without rewriting manuscript text.

Outputs:
  build/main_clean_refs_hardcoded.tex       main LaTeX with tables/figures removed and refs hard-coded
  build/tables_extracted.tex                raw LaTeX table environments, no preamble
  build/figure_captions.tex                 raw LaTeX figure legends, no preamble
  build/figures/                            copied figure files found in \includegraphics commands
  build/manuscript.docx                     pandoc-converted main Word file, if pandoc succeeds
  build/tables_standalone.tex               complete LaTeX wrapper containing extracted tables only
  build/tables.docx                         standalone Word table document generated by Pandoc
  build/tables_parsed.docx                  fallback parsed Word tables generated with python-docx
  build/manifest.json                       labels, captions, copied figures, conversion status

Design intent:
  - Preserve prose exactly, except for hard-coding \ref-like commands and removing float environments.
  - Do not add Key Points, rewrite abstracts, or restructure the manuscript.
  - Extract tables and figure captions for journal submission workflows that want figure legends/tables at back.
  - Generate a standalone tables DOCX from the extracted LaTeX tables, with a parsed-table fallback.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

try:
    from docx import Document
    from docx.shared import Pt, Inches
except Exception:
    Document = None

FLOAT_ENVS = ("table", "table*", "figure", "figure*", "sidewaystable", "sidewaysfigure")

BIBLIOGRAPHY_STYLES = ("current", "apa", "apa-numbered", "vancouver", "ama")

# Minimal bundled CSL styles used when an official CSL file is not available locally.
# Users can pass --csl for a journal-specific style file.
BUNDLED_CSL: Dict[str, str] = {'apa-numbered': '<?xml version="1.0" encoding="utf-8"?>\n<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" default-locale="en-US">\n  <info>\n    <title>APA-like Numbered, Order of Appearance</title>\n    <id>https://zebralab.local/csl/apa-numbered-order</id>\n    <link href="https://zebralab.local/csl/apa-numbered-order" rel="self"/>\n    <author><name>Generated by generate_docx_submission.py</name></author>\n    <category citation-format="numeric"/>\n    <updated>2026-01-01T00:00:00+00:00</updated>\n  </info>\n  <macro name="author"><names variable="author"><name name-as-sort-order="all" sort-separator=", " initialize-with=". " delimiter=", " delimiter-precedes-last="always"/><substitute><text variable="title"/></substitute></names></macro>\n  <macro name="issued-year"><date variable="issued"><date-part name="year"/></date></macro>\n  <citation collapse="citation-number"><sort><key variable="citation-number"/></sort><layout prefix="[" suffix="]" delimiter=", "><text variable="citation-number"/></layout></citation>\n  <bibliography second-field-align="flush" entry-spacing="0"><sort><key variable="citation-number"/></sort><layout suffix="."><text variable="citation-number" suffix=". "/><text macro="author" suffix=" "/><text macro="issued-year" prefix="(" suffix="). "/><text variable="title" suffix=". "/><text variable="container-title" font-style="italic"/><group delimiter=", " prefix=", "><text variable="volume" font-style="italic"/><text variable="issue" prefix="(" suffix=")"/><text variable="page"/></group><text variable="DOI" prefix=". doi:"/></layout></bibliography>\n</style>\n', 'ama': '<?xml version="1.0" encoding="utf-8"?>\n<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" default-locale="en-US">\n  <info><title>AMA-like Numbered</title><id>https://zebralab.local/csl/ama-like</id><link href="https://zebralab.local/csl/ama-like" rel="self"/><author><name>Generated by generate_docx_submission.py</name></author><category citation-format="numeric"/><updated>2026-01-01T00:00:00+00:00</updated></info>\n  <macro name="author"><names variable="author"><name name-as-sort-order="all" sort-separator=" " initialize-with="" delimiter=", " delimiter-precedes-last="never"/><substitute><text variable="title"/></substitute></names></macro>\n  <macro name="issued-year"><date variable="issued"><date-part name="year"/></date></macro>\n  <citation collapse="citation-number"><sort><key variable="citation-number"/></sort><layout delimiter=","><text variable="citation-number"/></layout></citation>\n  <bibliography entry-spacing="0" second-field-align="flush"><sort><key variable="citation-number"/></sort><layout suffix="."><text variable="citation-number" suffix=". "/><text macro="author" suffix=". "/><text variable="title" suffix=". "/><text variable="container-title" font-style="italic" suffix=". "/><text macro="issued-year"/><group delimiter=";" prefix=";"><text variable="volume"/><text variable="issue" prefix="(" suffix=")"/></group><text variable="page" prefix=":"/><text variable="DOI" prefix=". doi:"/></layout></bibliography>\n</style>\n', 'vancouver': '<?xml version="1.0" encoding="utf-8"?>\n<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" default-locale="en-US">\n  <info><title>Vancouver-like Numbered</title><id>https://zebralab.local/csl/vancouver-like</id><link href="https://zebralab.local/csl/vancouver-like" rel="self"/><author><name>Generated by generate_docx_submission.py</name></author><category citation-format="numeric"/><updated>2026-01-01T00:00:00+00:00</updated></info>\n  <macro name="author"><names variable="author"><name name-as-sort-order="all" sort-separator=" " initialize-with="" delimiter=", " delimiter-precedes-last="never"/><substitute><text variable="title"/></substitute></names></macro>\n  <macro name="issued-year"><date variable="issued"><date-part name="year"/></date></macro>\n  <citation collapse="citation-number"><sort><key variable="citation-number"/></sort><layout prefix="(" suffix=")" delimiter=", "><text variable="citation-number"/></layout></citation>\n  <bibliography entry-spacing="0" second-field-align="flush"><sort><key variable="citation-number"/></sort><layout suffix="."><text variable="citation-number" suffix=". "/><text macro="author" suffix=". "/><text variable="title" suffix=". "/><text variable="container-title" suffix=". "/><text macro="issued-year"/><group prefix=";" delimiter=":"><text variable="volume"/><text variable="page"/></group><text variable="DOI" prefix=". doi:"/></layout></bibliography>\n</style>\n', 'apa': '<?xml version="1.0" encoding="utf-8"?>\n<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" default-locale="en-US">\n  <info><title>APA-like Author-Date</title><id>https://zebralab.local/csl/apa-like</id><link href="https://zebralab.local/csl/apa-like" rel="self"/><author><name>Generated by generate_docx_submission.py</name></author><category citation-format="author-date"/><updated>2026-01-01T00:00:00+00:00</updated></info>\n  <macro name="author"><names variable="author"><name name-as-sort-order="all" sort-separator=", " initialize-with=". " delimiter=", " delimiter-precedes-last="always"/><substitute><text variable="title"/></substitute></names></macro>\n  <macro name="author-short"><names variable="author"><name form="short" and="text" delimiter=", "/><substitute><text variable="title"/></substitute></names></macro>\n  <macro name="issued-year"><date variable="issued"><date-part name="year"/></date></macro>\n  <citation><sort><key macro="author"/><key variable="issued"/></sort><layout prefix="(" suffix=")" delimiter="; "><group delimiter=", "><text macro="author-short"/><text macro="issued-year"/></group></layout></citation>\n  <bibliography hanging-indent="true" entry-spacing="0"><sort><key macro="author"/><key variable="issued"/></sort><layout suffix="."><text macro="author" suffix=" "/><text macro="issued-year" prefix="(" suffix="). "/><text variable="title" suffix=". "/><text variable="container-title" font-style="italic"/><group delimiter=", " prefix=", "><text variable="volume" font-style="italic"/><text variable="issue" prefix="(" suffix=")"/><text variable="page"/></group><text variable="DOI" prefix=". https://doi.org/"/></layout></bibliography>\n</style>\n'}


@dataclass
class FloatBlock:
    kind: str
    env: str
    label: str
    caption: str
    number: int
    graphics: List[str]
    raw: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def strip_latex_comments_keep_escaped_percent(s: str) -> str:
    out_lines = []
    for line in s.splitlines():
        i = 0
        cut = len(line)
        while i < len(line):
            if line[i] == "%":
                # Count preceding backslashes. Even count means unescaped percent.
                bs = 0
                j = i - 1
                while j >= 0 and line[j] == "\\":
                    bs += 1
                    j -= 1
                if bs % 2 == 0:
                    cut = i
                    break
            i += 1
        out_lines.append(line[:cut])
    return "\n".join(out_lines)


def find_existing_tex(name: str, base_dir: Path) -> Optional[Path]:
    p = Path(name)
    candidates = []
    if p.suffix:
        candidates.append(base_dir / p)
    else:
        candidates.append(base_dir / (name + ".tex"))
        candidates.append(base_dir / name)
    for c in candidates:
        if c.exists():
            return c.resolve()
    return None


def inline_inputs(text: str, base_dir: Path, seen: Optional[set] = None) -> str:
    r"""Inline non-commented \input{} and \include{} recursively."""
    if seen is None:
        seen = set()

    pattern = re.compile(r"(?P<cmd>\\(?:input|include))\s*\{(?P<path>[^}]+)\}")

    def repl(match: re.Match) -> str:
        # Do not expand if a non-escaped % appears earlier on same line.
        line_start = text.rfind("\n", 0, match.start()) + 1
        prefix = text[line_start:match.start()]
        if re.search(r"(?<!\\)%", prefix):
            return match.group(0)
        raw_path = match.group("path").strip()
        target = find_existing_tex(raw_path, base_dir)
        if target is None:
            return match.group(0)
        if target in seen:
            return f"% [generate_docx_submission.py: skipped recursive input {raw_path}]"
        seen.add(target)
        sub = read_text(target)
        return "\n" + inline_inputs(sub, target.parent, seen) + "\n"

    return pattern.sub(repl, text)


def split_preamble_document(text: str) -> Tuple[str, str, str]:
    m = re.search(r"\\begin\{document\}", text)
    if not m:
        return text, "", ""
    e = re.search(r"\\end\{document\}", text)
    if not e:
        return text[:m.end()], text[m.end():], ""
    return text[:m.end()], text[m.end():e.start()], text[e.start():]


def parse_first_braced_arg(s: str, start: int) -> Tuple[Optional[str], int]:
    """Parse braced argument beginning at or after start. Returns (content, end_index)."""
    i = start
    while i < len(s) and s[i].isspace():
        i += 1
    if i >= len(s) or s[i] != "{":
        return None, start
    depth = 0
    out = []
    while i < len(s):
        ch = s[i]
        if ch == "{" and (i == 0 or s[i-1] != "\\"):
            depth += 1
            if depth > 1:
                out.append(ch)
        elif ch == "}" and (i == 0 or s[i-1] != "\\"):
            depth -= 1
            if depth == 0:
                return "".join(out), i + 1
            out.append(ch)
        else:
            out.append(ch)
        i += 1
    return None, start


def find_latex_command_arg(s: str, command: str) -> Optional[str]:
    pat = re.compile(r"\\" + re.escape(command) + r"\s*(?:\[[^\]]*\])?\s*")
    m = pat.search(s)
    if not m:
        return None
    arg, _ = parse_first_braced_arg(s, m.end())
    return arg


def find_all_labels(s: str) -> List[str]:
    return re.findall(r"\\label\s*\{([^}]+)\}", s)


def find_all_graphics(s: str) -> List[str]:
    paths = []
    pat = re.compile(r"\\includegraphics\s*(?:\[[^\]]*\])?\s*\{([^}]+)\}")
    for m in pat.finditer(s):
        paths.append(m.group(1).strip())
    return paths


def extract_floats(document_body: str) -> Tuple[str, List[FloatBlock], List[FloatBlock]]:
    # Match float environments non-greedily; floats normally do not nest.
    env_alt = "|".join(re.escape(e) for e in sorted(FLOAT_ENVS, key=len, reverse=True))
    pat = re.compile(r"\\begin\{(?P<env>" + env_alt + r")\}.*?\\end\{(?P=env)\}", re.DOTALL)
    floats: List[FloatBlock] = []
    table_n = 0
    fig_n = 0

    def repl(m: re.Match) -> str:
        nonlocal table_n, fig_n
        raw = m.group(0)
        env = m.group("env")
        kind = "table" if "table" in env else "figure"
        if kind == "table":
            table_n += 1
            n = table_n
        else:
            fig_n += 1
            n = fig_n
        labels = find_all_labels(raw)
        label = labels[0] if labels else f"{kind}:{n}"
        caption = find_latex_command_arg(raw, "caption") or ""
        graphics = find_all_graphics(raw)
        floats.append(FloatBlock(kind=kind, env=env, label=label, caption=caption, number=n, graphics=graphics, raw=raw))
        return f"\n% [Float removed for Word conversion: {kind} {n}, label={label}]\n"

    cleaned = pat.sub(repl, document_body)
    tables = [b for b in floats if b.kind == "table"]
    figures = [b for b in floats if b.kind == "figure"]
    return cleaned, tables, figures



def _skip_ws(text: str, i: int) -> int:
    while i < len(text) and text[i].isspace():
        i += 1
    return i


def parse_bracket_arg(s: str, start: int) -> Tuple[Optional[str], int]:
    """Parse optional bracket argument beginning at or after start."""
    i = _skip_ws(s, start)
    if i >= len(s) or s[i] != "[":
        return None, start
    depth = 0
    out = []
    while i < len(s):
        ch = s[i]
        if ch == "[" and (i == 0 or s[i-1] != "\\"):
            depth += 1
            if depth > 1:
                out.append(ch)
        elif ch == "]" and (i == 0 or s[i-1] != "\\"):
            depth -= 1
            if depth == 0:
                return "".join(out), i + 1
            out.append(ch)
        else:
            out.append(ch)
        i += 1
    return None, start


def _consume_command_name(text: str, i: int) -> int:
    """Return index after a LaTeX control sequence starting at i."""
    if i >= len(text) or text[i] != "\\":
        return i
    j = i + 1
    while j < len(text) and (text[j].isalpha() or text[j] == "@"):
        j += 1
    if j == i + 1 and j < len(text):
        return j + 1
    return j


def remove_named_command_invocations(text: str, names: List[str], max_braced_args: int = 8) -> str:
    r"""Remove formatting-only commands with their common braced/optional arguments.

    This is deliberately conservative: it is meant for preamble-only commands such as
    \titlespacing and \titleformat that pandoc can otherwise leak into the DOCX as text.
    """
    if not names:
        return text
    name_alt = "|".join(re.escape(n) for n in sorted(names, key=len, reverse=True))
    pat = re.compile(r"\\(?P<name>" + name_alt + r")\*?")
    out = []
    pos = 0
    for m in pat.finditer(text):
        out.append(text[pos:m.start()])
        i = m.end()
        # consume optional args and braced args in the usual titlesec command forms
        for _ in range(2):
            arg, j = parse_bracket_arg(text, i)
            if arg is None:
                break
            i = j
        for _ in range(max_braced_args):
            arg, j = parse_first_braced_arg(text, i)
            if arg is None:
                break
            i = j
            # Some commands have optional args after braced args, e.g. \titlespacing*... [right]
            opt, jj = parse_bracket_arg(text, i)
            if opt is not None:
                i = jj
        # remove trailing whitespace on the same physical line, but preserve paragraph boundary
        while i < len(text) and text[i] in " \t":
            i += 1
        pos = i
    out.append(text[pos:])
    return "".join(out)


def remove_section_macro_definitions(preamble: str) -> str:
    r"""Remove custom definitions of sectioning commands from the preamble.

    Pandoc does not execute LaTeX classes/packages the way TeX does. When a source or
    custom preamble redefines \section using \@startsection or titlesec spacing commands,
    pandoc may treat numeric spacing arguments (for example `1pt -3ex 0ex .1pt`) as
    literal document text. Removing only these preamble-level formatting definitions keeps
    the real body commands such as \section*{Introduction} intact.
    """
    targets = {"section", "subsection", "subsubsection", "paragraph", "subparagraph"}
    out = []
    i = 0
    while i < len(preamble):
        removed = False

        # \def\section...{...} / \gdef\section...{...} / \xdef\section...{...}
        for cmd in ("def", "gdef", "xdef", "edef"):
            prefix = "\\" + cmd
            if preamble.startswith(prefix, i):
                j = _skip_ws(preamble, i + len(prefix))
                if preamble.startswith("\\", j):
                    k = _consume_command_name(preamble, j)
                    name = preamble[j+1:k]
                    if name in targets:
                        # Skip possible parameter text (#1, [..], etc.) until definition body.
                        b = preamble.find("{", k)
                        if b != -1:
                            _, end = parse_first_braced_arg(preamble, b)
                            if end != b:
                                i = end
                                removed = True
                                break
        if removed:
            continue

        # \renewcommand{\section}[...]{...}, \renewcommand\section[...]{...}
        m = re.match(r"\\(?:re)?newcommand\*?", preamble[i:])
        if m:
            j = _skip_ws(preamble, i + m.end())
            name = None
            if j < len(preamble) and preamble[j] == "{":
                arg, k = parse_first_braced_arg(preamble, j)
                if arg and arg.strip().startswith("\\"):
                    name = arg.strip()[1:]
                    j = k
            elif preamble.startswith("\\", j):
                k = _consume_command_name(preamble, j)
                name = preamble[j+1:k]
                j = k
            if name in targets:
                # Optional [nargs] and [default]
                for _ in range(2):
                    arg, k = parse_bracket_arg(preamble, j)
                    if arg is None:
                        break
                    j = k
                _, end = parse_first_braced_arg(preamble, j)
                if end != j:
                    i = end
                    continue

        out.append(preamble[i])
        i += 1
    return "".join(out)


def sanitize_preamble_for_pandoc(preamble: str) -> str:
    r"""Drop LaTeX layout instructions that commonly leak into pandoc DOCX output.

    This does not touch the manuscript body and therefore preserves the visible manuscript text.
    """
    p = remove_section_macro_definitions(preamble)
    p = remove_named_command_invocations(
        p,
        [
            "titlespacing", "titleformat", "titleformat*", "titleclass",
            "setsecheadstyle", "setsubsecheadstyle", "setsubsubsecheadstyle",
        ],
        max_braced_args=8,
    )
    # If a bare \@startsection survived outside a macro definition, remove its six args.
    p = remove_named_command_invocations(p, ["@startsection"], max_braced_args=8)
    return p

def run_pdflatex_for_aux(source: Path, outdir: Path) -> Tuple[Dict[str, str], str]:
    """Compile twice and parse aux labels. Returns mapping and log text."""
    outdir.mkdir(parents=True, exist_ok=True)
    cmd = ["pdflatex", "-interaction=nonstopmode", "-file-line-error", "-output-directory", str(outdir), str(source.name)]
    log = []
    for _ in range(2):
        try:
            p = subprocess.run(cmd, cwd=str(source.parent), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=120)
            log.append(p.stdout)
            if p.returncode != 0:
                break
        except Exception as e:
            log.append(f"pdflatex failed: {e}")
            break
    aux = outdir / (source.stem + ".aux")
    mapping: Dict[str, str] = {}
    if aux.exists():
        aux_text = read_text(aux)
        # Basic LaTeX \newlabel format. Good enough for figure/table/section refs.
        for m in re.finditer(r"\\newlabel\{([^}]+)\}\{\{([^}]*)\}\{([^}]*)\}", aux_text):
            mapping[m.group(1)] = m.group(2)
    return mapping, "\n".join(log)


def fallback_label_map(tables: List[FloatBlock], figures: List[FloatBlock]) -> Dict[str, str]:
    mapping = {}
    for t in tables:
        if t.label:
            mapping[t.label] = str(t.number)
    for f in figures:
        if f.label:
            mapping[f.label] = str(f.number)
    return mapping


def hardcode_refs(text: str, label_map: Dict[str, str]) -> str:
    def repl_ref(m: re.Match) -> str:
        cmd = m.group(1)
        label = m.group(2).strip()
        val = label_map.get(label, "??")
        if cmd == "eqref":
            return f"({val})"
        return val
    text = re.sub(r"\\(ref|pageref|eqref)\s*\{([^}]+)\}", repl_ref, text)
    # Common autoref-like cases.
    def repl_auto(m: re.Match) -> str:
        label = m.group(2).strip()
        val = label_map.get(label, "??")
        if label.lower().startswith("fig") or "fig" in label.lower():
            return f"Figure {val}"
        if label.lower().startswith("tab") or "table" in label.lower():
            return f"Table {val}"
        return val
    text = re.sub(r"\\(autoref|cref|Cref)\s*\{([^}]+)\}", repl_auto, text)
    return text


def copy_graphics(figures: List[FloatBlock], source_dir: Path, out_fig_dir: Path) -> Dict[str, List[str]]:
    out_fig_dir.mkdir(parents=True, exist_ok=True)
    copied: Dict[str, List[str]] = {}
    exts = ["", ".pdf", ".png", ".jpg", ".jpeg", ".tif", ".tiff", ".eps"]
    for fig in figures:
        copied[fig.label] = []
        for g in fig.graphics:
            found = None
            for ext in exts:
                p = source_dir / (g + ext if not Path(g).suffix else g)
                if p.exists():
                    found = p
                    break
            if found is None:
                continue
            dest = out_fig_dir / found.name
            try:
                shutil.copy2(found, dest)
                copied[fig.label].append(str(dest))
            except Exception:
                pass
    return copied


def make_figure_captions_tex(figures: List[FloatBlock], label_map: Dict[str, str]) -> str:
    chunks = []
    for fig in figures:
        cap = hardcode_refs(fig.caption, label_map)
        chunks.append(f"\\paragraph{{Figure {fig.number}.}} {cap}\n")
    return "\n".join(chunks).strip() + "\n"


def make_tables_raw_tex(tables: List[FloatBlock], label_map: Dict[str, str]) -> str:
    return "\n\n".join(hardcode_refs(t.raw, label_map) for t in tables).strip() + "\n"


def insert_figure_legends_before_end(clean_tex: str, fig_legends: str) -> str:
    if not fig_legends.strip():
        return clean_tex
    insertion = "\n\n\\clearpage\n\\section*{Figure Legends}\n" + fig_legends + "\n"
    # If bibliography exists, put figure legends after it but before \end{document}. If no end, append.
    m = re.search(r"\\end\{document\}", clean_tex)
    if m:
        return clean_tex[:m.start()] + insertion + clean_tex[m.start():]
    return clean_tex + insertion



def find_system_csl(style: str) -> Optional[Path]:
    """Find a locally installed CSL file for common styles, if available."""
    candidates = {
        "apa": ["apa.csl"],
        "vancouver": ["vancouver.csl"],
        "ama": ["american-medical-association.csl", "ama.csl"],
    }.get(style, [])
    search_dirs = [
        Path("/usr/share/texlive/texmf-dist/tex/latex/citation-style-language/styles"),
        Path("/usr/share/citation-style-language/styles"),
        Path.home() / ".local/share/citation-style-language/styles",
    ]
    for d in search_dirs:
        for name in candidates:
            c = d / name
            if c.exists():
                return c.resolve()
    return None


def resolve_csl(style: str, csl_override: Optional[Path], outdir: Path) -> Tuple[Optional[Path], str]:
    """Resolve the CSL path for a requested bibliography style.

    style='current' preserves the old behavior: use citeproc without passing an explicit CSL.
    Other styles use an official local CSL when one is installed, otherwise a bundled minimal CSL.
    """
    if csl_override:
        if not csl_override.exists():
            raise FileNotFoundError(f"CSL file not found: {csl_override}")
        return csl_override.resolve(), "custom CSL"
    if style == "current":
        return None, "current/default pandoc citeproc style"
    official = find_system_csl(style)
    if official is not None and style != "apa-numbered":
        return official, f"system CSL: {official}"
    if style not in BUNDLED_CSL:
        raise ValueError(f"Unknown bibliography style '{style}'. Choices: {', '.join(BIBLIOGRAPHY_STYLES)}")
    csl_dir = outdir / "csl"
    csl_dir.mkdir(parents=True, exist_ok=True)
    csl_path = csl_dir / f"{style}.csl"
    write_text(csl_path, BUNDLED_CSL[style])
    return csl_path.resolve(), f"bundled CSL: {csl_path}"


def find_bibliography_files(latex_text: str, source_dir: Path) -> List[Path]:
    """Find .bib files referenced by \bibliography{...} or \addbibresource{...}."""
    bibs: List[Path] = []
    seen = set()

    def add_one(raw: str) -> None:
        raw = raw.strip()
        if not raw:
            return
        p = Path(raw)
        if not p.suffix:
            p = Path(str(p) + ".bib")
        candidates = [p, source_dir / p]
        for c in candidates:
            if c.exists():
                r = c.resolve()
                if r not in seen:
                    seen.add(r)
                    bibs.append(r)
                return
        # Keep the source-relative path even if it does not exist; pandoc output will make the failure explicit.
        r = (source_dir / p).resolve()
        if r not in seen:
            seen.add(r)
            bibs.append(r)

    for m in re.finditer(r"\\bibliography\s*\{([^}]+)\}", latex_text):
        for item in m.group(1).split(','):
            add_one(item)
    for m in re.finditer(r"\\addbibresource(?:\[[^\]]*\])?\s*\{([^}]+)\}", latex_text):
        add_one(m.group(1))
    return bibs


def run_pandoc(
    clean_tex: Path,
    out_docx: Path,
    source_dir: Path,
    reference_doc: Optional[Path],
    todocx: Optional[Path],
    bibliography_style: str,
    csl_path: Optional[Path],
) -> Dict[str, str]:
    status = {"main_docx": "not attempted"}
    out_docx.parent.mkdir(parents=True, exist_ok=True)
    latex_text = read_text(clean_tex)
    bib_files = find_bibliography_files(latex_text, source_dir)
    status["bibliography_style"] = bibliography_style
    status["bibliography_files"] = ";".join(str(b) for b in bib_files)
    status["csl"] = str(csl_path) if csl_path else "pandoc default/current"

    # Prefer the provided todocx script only for the legacy/default bibliography path.
    # Non-default styles must be routed through direct pandoc so --csl is honored.
    if todocx and todocx.exists() and bibliography_style == "current" and csl_path is None:
        try:
            p = subprocess.run(["bash", str(todocx.resolve()), clean_tex.name], cwd=str(clean_tex.parent), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=180)
            generated = clean_tex.parent / "manuscript.docx"
            if p.returncode == 0 and generated.exists():
                if generated.resolve() != out_docx.resolve():
                    shutil.copy2(generated, out_docx)
                status["main_docx"] = "created with todocx script"
                status["todocx_output"] = p.stdout[-4000:]
                return status
            status["todocx_output"] = p.stdout[-4000:]
            status["main_docx"] = "todocx failed; attempting direct pandoc fallback"
        except Exception as e:
            status["main_docx"] = f"todocx failed ({e}); attempting direct pandoc fallback"

    def call_pandoc(use_citeproc: bool) -> Tuple[int, str, List[str]]:
        cmd = ["pandoc", str(clean_tex), "--from=latex", "--to=docx", "--mathml"]
        if use_citeproc:
            cmd.append("--citeproc")
            if csl_path:
                cmd.append(f"--csl={csl_path}")
            for bib in bib_files:
                cmd.append(f"--bibliography={bib}")
        if reference_doc and reference_doc.exists():
            cmd.append(f"--reference-doc={reference_doc}")
        cmd.extend(["-o", str(out_docx)])
        p = subprocess.run(cmd, cwd=str(source_dir), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=180)
        return p.returncode, p.stdout, cmd

    try:
        rc, out, cmd = call_pandoc(use_citeproc=True)
        status["pandoc_output"] = out[-4000:]
        status["pandoc_command"] = " ".join(cmd)
        if rc == 0 and out_docx.exists():
            status["main_docx"] = "created with direct pandoc"
            return status
        # Missing .bib files are common in partial source uploads. Rerun without citeproc so a DOCX can still be generated.
        if "File " in out and ".bib" in out:
            rc2, out2, cmd2 = call_pandoc(use_citeproc=False)
            status["pandoc_no_citeproc_output"] = out2[-4000:]
            status["pandoc_no_citeproc_command"] = " ".join(cmd2)
            if rc2 == 0 and out_docx.exists():
                status["main_docx"] = "created with direct pandoc without citeproc; citations not processed"
                return status
        status["main_docx"] = f"pandoc failed with code {rc}"
    except Exception as e:
        status["main_docx"] = f"pandoc exception: {e}"
    return status


def split_rows_latex(tabular_body: str) -> List[str]:
    rows = []
    buf = []
    depth = 0
    i = 0
    while i < len(tabular_body):
        ch = tabular_body[i]
        if ch == "{" and (i == 0 or tabular_body[i-1] != "\\"):
            depth += 1
        elif ch == "}" and (i == 0 or tabular_body[i-1] != "\\") and depth > 0:
            depth -= 1
        if ch == "\\" and i + 1 < len(tabular_body) and tabular_body[i+1] == "\\" and depth == 0:
            rows.append("".join(buf))
            buf = []
            i += 2
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        rows.append(tail)
    return rows


def split_cells_latex(row: str) -> List[str]:
    cells = []
    buf = []
    depth = 0
    i = 0
    while i < len(row):
        ch = row[i]
        if ch == "{" and (i == 0 or row[i-1] != "\\"):
            depth += 1
        elif ch == "}" and (i == 0 or row[i-1] != "\\") and depth > 0:
            depth -= 1
        if ch == "&" and depth == 0 and (i == 0 or row[i-1] != "\\"):
            cells.append("".join(buf))
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    cells.append("".join(buf))
    return cells


def clean_latex_cell(s: str) -> str:
    s = strip_latex_comments_keep_escaped_percent(s)
    # Remove table-only commands.
    s = re.sub(r"\\(?:hline|toprule|midrule|bottomrule|cmidrule)(?:\[[^\]]*\])?(?:\{[^}]*\})?", "", s)
    s = re.sub(r"\\rowcolor\s*\{[^}]*\}", "", s)
    s = re.sub(r"\\fontsize\s*\{[^}]*\}\s*\{[^}]*\}\s*\\selectfont", "", s)
    s = re.sub(r"\\(?:centering|raggedright|raggedleft|arraybackslash|selectfont|small|footnotesize|scriptsize|tiny|normalsize)", "", s)
    # Unwrap common formatting commands repeatedly.
    for _ in range(5):
        old = s
        s = re.sub(r"\\(?:textbf|textit|emph|texttt|mathrm|mathbf|mathit)\s*\{([^{}]*)\}", r"\1", s)
        s = re.sub(r"\\multicolumn\s*\{\d+\}\s*\{[^}]*\}\s*\{([^{}]*)\}", r"\1", s)
        if s == old:
            break
    replacements = {
        r"\%": "%", r"\_": "_", r"\&": "&", r"\$": "$", r"\#": "#",
        r"\newline": "\n", r"\pm": "±", r"\times": "×", r"\leq": "≤", r"\geq": "≥",
        r"\rho": "ρ", r"\neg": "¬", r"\vert": "|", r"\mid": "|", r"\star": "*",
        r"\zebra": "ZeBRA", r"\textwidth": "", r"\EXTENDEDDATA": "", r"\SUPPLEMENTARY": "Supplementary",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    s = re.sub(r"\$([^$]*)\$", r"\1", s)
    s = re.sub(r"\\\((.*?)\\\)", r"\1", s)
    s = re.sub(r"\\\[(.*?)\\\]", r"\1", s, flags=re.DOTALL)
    s = re.sub(r"\\[a-zA-Z]+\*?(?:\[[^\]]*\])?", "", s)
    s = s.replace("{", "").replace("}", "")
    s = s.replace("~", " ").replace("--", "–")
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n\s+", "\n", s)
    return s.strip()


def extract_tabular(table_raw: str) -> Optional[List[List[str]]]:
    m = re.search(r"\\begin\{tabular\}\s*\{", table_raw)
    if not m:
        return None
    # Skip tabular column spec using balanced parse.
    _, start_body = parse_first_braced_arg(table_raw, m.end() - 1)
    end = re.search(r"\\end\{tabular\}", table_raw[start_body:], flags=re.DOTALL)
    if not end:
        return None
    body = table_raw[start_body:start_body + end.start()]
    rows = []
    for row in split_rows_latex(body):
        cleaned_row = re.sub(r"\\(?:hline|toprule|midrule|bottomrule)\b", "", row).strip()
        cleaned_row = re.sub(r"\\rowcolor\s*\{[^}]*\}", "", cleaned_row).strip()
        if not cleaned_row:
            continue
        cells = [clean_latex_cell(c) for c in split_cells_latex(cleaned_row)]
        if any(cells):
            rows.append(cells)
    # Normalize row lengths.
    if rows:
        maxcols = max(len(r) for r in rows)
        rows = [r + [""] * (maxcols - len(r)) for r in rows]
    return rows or None


def build_tables_docx(tables: List[FloatBlock], out_docx: Path, label_map: Dict[str, str]) -> Dict[str, str]:
    status = {"tables_docx": "not attempted"}
    if Document is None:
        status["tables_docx"] = "python-docx unavailable"
        return status
    doc = Document()
    styles = doc.styles
    styles["Normal"].font.name = "Times New Roman"
    styles["Normal"].font.size = Pt(11)
    for i, tb in enumerate(tables, 1):
        cap = clean_latex_cell(hardcode_refs(tb.caption, label_map))
        p = doc.add_paragraph()
        run = p.add_run(f"Table {tb.number}. {cap}")
        run.bold = True
        rows = extract_tabular(hardcode_refs(tb.raw, label_map))
        if rows is None:
            p = doc.add_paragraph()
            p.add_run("[Could not parse tabular automatically. Raw LaTeX follows.]").italic = True
            p = doc.add_paragraph(hardcode_refs(tb.raw, label_map))
            p.style = styles["Normal"]
        else:
            table = doc.add_table(rows=len(rows), cols=max(len(r) for r in rows))
            table.style = "Table Grid"
            for r_idx, row in enumerate(rows):
                for c_idx, val in enumerate(row):
                    cell = table.cell(r_idx, c_idx)
                    cell.text = val
                    for para in cell.paragraphs:
                        for run in para.runs:
                            run.font.name = "Times New Roman"
                            run.font.size = Pt(9)
            # bold first row
            for cell in table.rows[0].cells:
                for para in cell.paragraphs:
                    for run in para.runs:
                        run.bold = True
        if i != len(tables):
            doc.add_page_break()
    out_docx.parent.mkdir(parents=True, exist_ok=True)
    doc.save(out_docx)
    status["tables_docx"] = "created with python-docx"
    return status



def make_tables_standalone_tex(tables_tex: str) -> str:
    r'''Create a complete LaTeX document containing only extracted tables.

    The extracted table file deliberately has no preamble. This wrapper gives
    Pandoc enough standard table/macro definitions to convert the tables into a
    standalone DOCX without touching the manuscript text.
    '''
    preamble = r'''
\documentclass[12pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{booktabs}
\usepackage{array}
\usepackage{multirow}
\usepackage{longtable}
\usepackage[table]{xcolor}
\usepackage{graphicx}
\usepackage{makecell}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{caption}
\newcolumntype{L}[1]{>{\raggedright\arraybackslash}p{#1}}
\newcolumntype{R}[1]{>{\raggedleft\arraybackslash}p{#1}}
\newcolumntype{C}[1]{>{\centering\arraybackslash}p{#1}}
\providecommand{\zebra}{ZeBRA}
\providecommand{\Zebra}{ZeBRA}
\providecommand{\SI}{SI/SA}
\providecommand{\SISA}{SI/SA}
\providecommand{\EXTENDEDDATA}{Extended Data}
\providecommand{\SUPPLEMENTARY}{Supplementary}
\providecommand{\mnp}[2]{\begin{minipage}{#1}#2\end{minipage}}
\providecommand{\pp}{percentage points}
\begin{document}
\section*{Tables}
'''.strip()
    end = r'''
\end{document}
'''.strip()
    return preamble + "\n\n" + tables_tex.strip() + "\n\n" + end + "\n"


def run_pandoc_tables(standalone_tex: Path, out_docx: Path, reference_doc: Optional[Path]) -> Dict[str, str]:
    '''Convert the standalone tables LaTeX wrapper to DOCX using Pandoc.'''
    status = {"tables_docx": "not attempted"}
    out_docx.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "pandoc",
        str(standalone_tex),
        "--from=latex",
        "--to=docx",
        "--mathml",
        "-o",
        str(out_docx),
    ]
    if reference_doc and reference_doc.exists():
        cmd.insert(-2, f"--reference-doc={reference_doc}")
    try:
        p = subprocess.run(cmd, cwd=str(standalone_tex.parent), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=180)
        status["tables_pandoc_command"] = " ".join(cmd)
        status["tables_pandoc_output"] = p.stdout[-4000:]
        if p.returncode == 0 and out_docx.exists():
            status["tables_docx"] = "created with pandoc from tables_standalone.tex"
        else:
            status["tables_docx"] = f"pandoc tables conversion failed with code {p.returncode}"
    except Exception as e:
        status["tables_docx"] = f"pandoc tables conversion exception: {e}"
    return status

def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Word-submission intermediates from LaTeX without rewriting text.")
    ap.add_argument("source", help="Main .tex file")
    ap.add_argument("--outdir", default="submission_build", help="Output directory")
    ap.add_argument("--todocx", default=None, help="Optional todocx.sh-like converter script")
    ap.add_argument("--reference-doc", default=None, help="Optional pandoc reference DOCX")
    ap.add_argument("--bibliography-style", "--bib-style", default="current", choices=BIBLIOGRAPHY_STYLES, help="Citation/bibliography style: current preserves old behavior; apa-numbered gives APA-like references numbered in order of appearance")
    ap.add_argument("--csl", default=None, help="Optional custom CSL file. Overrides --bibliography-style when supplied.")
    ap.add_argument("--list-bibliography-styles", action="store_true", help="Print supported bibliography styles and exit")
    ap.add_argument("--no-pandoc", action="store_true", help="Do not run pandoc/todocx for main DOCX")
    ap.add_argument("--no-tables-docx", action="store_true", help="Do not generate standalone/parsed DOCX files for extracted tables")
    ap.add_argument("--no-pdflatex", action="store_true", help="Do not compile source to obtain ref numbers")
    ap.add_argument("--no-sanitize-section-formatting", action="store_true", help="Do not strip LaTeX section-formatting macros from the preamble before pandoc")
    args = ap.parse_args()
    if args.list_bibliography_styles:
        print("\n".join(BIBLIOGRAPHY_STYLES))
        return 0

    source = Path(args.source).resolve()
    outdir = Path(args.outdir).resolve()
    source_dir = source.parent
    outdir.mkdir(parents=True, exist_ok=True)

    raw = read_text(source)
    expanded = inline_inputs(raw, source_dir)
    # Remove comments before float extraction and Word conversion. This avoids treating commented-out tables/figures as live content.
    expanded_nocomments = strip_latex_comments_keep_escaped_percent(expanded)
    preamble, body, enddoc = split_preamble_document(expanded_nocomments)
    if not args.no_sanitize_section_formatting:
        preamble = sanitize_preamble_for_pandoc(preamble)

    # Extract floats after inputs have been inlined.
    body_without_floats, tables, figures = extract_floats(body)

    # Compile original source to get hard-coded ref labels.
    aux_log = ""
    label_map = {}
    if not args.no_pdflatex:
        label_map, aux_log = run_pdflatex_for_aux(source, outdir / "latex_aux")
    fallback = fallback_label_map(tables, figures)
    # For extracted floats, prefer extraction order over aux labels. Aux compilation may fail or include supplemental numbering.
    for k, v in fallback.items():
        label_map[k] = v

    body_hard = hardcode_refs(body_without_floats, label_map)
    fig_legends = make_figure_captions_tex(figures, label_map)
    clean_tex = preamble + body_hard + enddoc
    clean_tex = insert_figure_legends_before_end(clean_tex, fig_legends)
    clean_tex = hardcode_refs(clean_tex, label_map)

    clean_path = outdir / "main_clean_refs_hardcoded.tex"
    tables_path = outdir / "tables_extracted.tex"
    figcap_path = outdir / "figure_captions.tex"
    tables_standalone_path = outdir / "tables_standalone.tex"
    expanded_path = outdir / "main_expanded_inputs.tex"
    write_text(expanded_path, expanded_nocomments)
    write_text(clean_path, clean_tex)
    tables_raw_tex = make_tables_raw_tex(tables, label_map)
    write_text(tables_path, tables_raw_tex)
    write_text(tables_standalone_path, make_tables_standalone_tex(tables_raw_tex))
    write_text(figcap_path, fig_legends)

    copied = copy_graphics(figures, source_dir, outdir / "figures")

    status = {}
    reference_doc = Path(args.reference_doc).resolve() if args.reference_doc else None
    csl_path, csl_status = resolve_csl(args.bibliography_style, Path(args.csl).resolve() if args.csl else None, outdir)
    status["bibliography_style"] = args.bibliography_style
    status["csl_status"] = csl_status
    status["csl_path"] = str(csl_path) if csl_path else ""
    if not args.no_pandoc:
        status.update(run_pandoc(clean_path, outdir / "manuscript.docx", source_dir, reference_doc, Path(args.todocx).resolve() if args.todocx else None, args.bibliography_style, csl_path))
    if not args.no_tables_docx:
        # Preferred tables DOCX: a standalone Pandoc conversion from a complete LaTeX wrapper.
        status.update(run_pandoc_tables(tables_standalone_path, outdir / "tables.docx", reference_doc))

        # Fallback/QA tables DOCX: parsed editable Word tables generated with python-docx.
        parsed_status = build_tables_docx(tables, outdir / "tables_parsed.docx", label_map)
        status["tables_parsed_docx"] = parsed_status.get("tables_docx", "not attempted")

        # If Pandoc cannot convert the standalone tables file, keep the old editable-table output
        # as tables.docx so downstream scripts do not break.
        if not (outdir / "tables.docx").exists() and (outdir / "tables_parsed.docx").exists():
            shutil.copy2(outdir / "tables_parsed.docx", outdir / "tables.docx")
            status["tables_docx"] = "pandoc failed; created from parsed python-docx fallback"

    manifest = {
        "source": str(source),
        "outputs": {
            "expanded_tex": str(expanded_path),
            "clean_tex": str(clean_path),
            "tables_tex": str(tables_path),
            "tables_standalone_tex": str(tables_standalone_path),
            "figure_captions_tex": str(figcap_path),
            "main_docx": str(outdir / "manuscript.docx"),
            "tables_docx": str(outdir / "tables.docx"),
            "tables_parsed_docx": str(outdir / "tables_parsed.docx"),
            "figures_dir": str(outdir / "figures"),
        },
        "n_tables": len(tables),
        "n_figures": len(figures),
        "tables": [asdict(t) | {"raw": "[omitted]"} for t in tables],
        "figures": [asdict(f) | {"raw": "[omitted]", "copied_files": copied.get(f.label, [])} for f in figures],
        "label_map": label_map,
        "bibliography_style": args.bibliography_style,
        "csl_path": str(csl_path) if csl_path else "",
        "status": status,
        "aux_log_tail": aux_log[-4000:],
    }
    write_text(outdir / "manifest.json", json.dumps(manifest, indent=2, ensure_ascii=False))

    print(json.dumps({
        "outdir": str(outdir),
        "clean_tex": str(clean_path),
        "tables_tex": str(tables_path),
        "tables_standalone_tex": str(tables_standalone_path),
        "figure_captions_tex": str(figcap_path),
        "main_docx_status": status.get("main_docx"),
        "tables_docx_status": status.get("tables_docx"),
        "tables_parsed_docx_status": status.get("tables_parsed_docx"),
        "bibliography_style": args.bibliography_style,
        "csl_status": csl_status,
        "n_tables": len(tables),
        "n_figures": len(figures),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
